### ISSUE TITLE
1.0.2 branch not pushed to packagist

### ISSUE THREAD

**Issue by trq** [jcroll/foursquare-api-bundle#2]
Looks like https://github.com/jcroll/foursquare-api-bundle/tree/v.1.0.2 hasn't made it to packagist. Can this be done manually please?

Also, I'm thinking that may have needed to be a 1.1.0 as it breaks semver?

**Comment by trq** [comment]
Actually, I see now why this wasn't pushed to packagist, it's an invalid tag.

v.1.0.2 should be v1.0.2

And IMO, should really be v1.1.0 anyway.

**Comment by jcroll** [comment]
@trq please see new tag `v1.1.0`: https://github.com/jcroll/foursquare-api-bundle/releases/tag/v1.1.0

Closing, please let me know if there are other issues.
