### ISSUE TITLE
BC Change

### ISSUE THREAD

**Issue by trq** [jcroll/foursquare-api-bundle#7]
Currently, this package relies upon `"jcroll/foursquare-api-client": ">=1"` which provides a `FoursquareClient` which simply extends the `GuzzleClient`.

Recently [these](https://github.com/jcroll/foursquare-api-client/commit/4558b0ddd026b49550ce6c31c3a84c9ae396c859) changes were made and a tag created at `v3.0.0`.

For this bundle to avoid BC breaks, I believe we should tag a version as `v1.1.5` which uses `"jcroll/foursquare-api-client": ">=1,<=3"` (or an equivalent) and then tag another version as `v.2.0.0` to use `"jcroll/foursquare-api-client": "~3"`.

Thoughts?

**Comment by jcroll** [comment]
@trq please just define the `jcroll/foursquare-api-client` version you want to use in your own `package.json` and let me know if you can't get that to work.
