### ISSUE TITLE
An error after upgrade

### ISSUE THREAD

**Issue by kopaygorodsky** [jcroll/foursquare-api-bundle#8]
There is an error executing the venues\/categories command: cURL error 6: Couldn't resolve host 'venues' (see http:\/\/curl.haxx.se\/libcurl\/c\/libcurl-errors.html)

guzzle works if I do this test, so the problem in your client:
```
$client = new \GuzzleHttp\Client();
 $res = $client->request('GET', 'https://api.foursquare.com/v2/venues/40a55d80f964a52020f31ee3?client_id=****&client_secret=***&v=20170113');
 echo $res->getStatusCode(); //200
```

**Comment by jcroll** [comment]
Hi @kopaygorodsky I'm closing this as you're not even using the client service:
```
$client = $this->container->get('jcroll_foursquare_client');
```

which makes me wonder whether you're even using this library.

If an issue needs to made in the client library please do so there: https://github.com/jcroll/foursquare-api-client

**Comment by kopaygorodsky** [comment]
@jcroll, sorry, I've described wrong. I use  bundle in usual way, like 
```
 $categoriesCom = $this->client->getCommand('venues/categories');
 $response = $this->client->execute($categoriesCom);
```
and I get error
`There was an error executing the venues/explore command: cURL error 6: Couldn't resolve host 'venues' (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)`,
but then I tried another way(that I described at the top, it was only for test) to call api with guzzle and it works, so I think the problem in client.

**Comment by kopaygorodsky** [comment]
I tested on default symfony instance
<img width="995" alt="screen shot 2017-01-15 at 4 57 17 pm" src="https://cloud.githubusercontent.com/assets/2415637/21963454/c8e2ee86-db43-11e6-90c0-b765f6a32dcd.png">

Controller:
```
$client = $this->get('jcroll_foursquare_client');
        $command = $client->getCommand('venues/categories');
        $resp = $client->execute($command);
```

config:
```
jcroll_foursquare_api:
    client_id: '%foursquare_client_id%'
    client_secret: '%foursquare_client_secret%'
```
